"""Seed a large synthetic event directly into the database, for load testing.

This is the Phase 5 load pass's own tool, generalised and committed: that pass
seeded 200 submissions / 50 judges / ~1,000 ballots / 1,500 votes "directly
into a running instance" (see ARCHITECTURE.md's "Measured, not assumed, at
5-10x the seeded fixtures") but never checked the script in. This one is
checked in, and goes further -- 1,000+ submissions, 500+ judges, 50,000+
votes, 100,000+ audit events -- to answer the same question at the next
order of magnitude up.

Run against the compose stack's Postgres, from the host, using the backend's
own virtualenv so it sees the same SQLAlchemy models the app does:

    DATABASE_URL=postgresql+psycopg://dogfood:dogfood@localhost:55432/dogfood \\
        backend/.venv/Scripts/python.exe scripts/load_test/seed_scale.py

(Port 55432 assumes the stack was brought up with `DOGFOOD_DB_PORT=55432`,
the workaround for a host Postgres already on 5432 -- see docker-compose.yml
and README.md.)

Writes go straight to the tables through the same ORM models `app/` uses, not
through the API -- 150,000+ rows is not something anyone should wait on FastAPI
request/response overhead plus per-request auth for, and this script is testing
what happens *after* that data exists, not the write paths that normally
create it (those already have their own tests). The one exception is the audit
log: `app.audit.record()`'s hash chain is reused byte-for-byte
(`_hash_fields`/`_chain_hash`, imported, not reimplemented) so the 100,000+
rows this seeds are real, verifiable links -- `GET /api/audit/verify` cannot
tell them apart from ones a real request wrote one at a time. Chaining still
needs `record()`'s advisory lock (a concurrent real write during the seed
would otherwise compute the same "previous hash" this script just read), and
the identity sequence backing `seq` needs to be pushed forward afterward,
since inserting explicit values with `OVERRIDING SYSTEM VALUE` does not do
that on its own -- skip it and the very next real audit write collides on
`uq_audit_log_seq`.

Idempotent at the event level, not additive: re-running this deletes any
prior `load-test` event (cascades to its teams/submissions/judges/
assignments/scores/voters/votes) and rebuilds it fresh, so the numbers this
prints always describe exactly one seed pass, never several stacked on top of
each other. Audit rows are the one thing that outlives the event (`event_id`
is `ON DELETE SET NULL`, on purpose -- see `AuditEntry`'s own docstring), so
re-running does add another 100,000+ of those; this script is meant to be run
once per measurement session, not on every container start like `app.seed`.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import random
import sys
import time
import uuid
from datetime import timedelta
from decimal import Decimal
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[2] / "backend"
sys.path.insert(0, str(BACKEND))

from sqlalchemy import create_engine, delete, select, text  # noqa: E402
from sqlalchemy.orm import Session, sessionmaker  # noqa: E402

from app.audit import _chain_hash, _hash_fields  # noqa: E402
from app.models import (  # noqa: E402
    AssignmentStatus,
    AuditAction,
    AuditEntry,
    Event,
    Judge,
    JudgeAssignment,
    Role,
    RubricCriterion,
    Score,
    Submission,
    SubmissionStatus,
    Team,
    TeamMember,
    TeamRole,
    User,
    Vote,
    Voter,
    VotingAccess,
    VotingMethod,
    utcnow,
)
from app.security import hash_password  # noqa: E402

EVENT_SLUG = "load-test"
NS = uuid.UUID("6c9a1f0e-1a2b-4c3d-9e8f-7a6b5c4d3e2f")


def _id(kind: str, key: str) -> uuid.UUID:
    return uuid.uuid5(NS, f"{kind}:{key}")


def _engine():
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise SystemExit(
            "Set DATABASE_URL first, e.g.\n"
            "  DATABASE_URL=postgresql+psycopg://dogfood:dogfood@localhost:55432/dogfood"
        )
    return create_engine(url, future=True)


def _delete_existing_event(db: Session) -> None:
    existing = db.execute(select(Event).where(Event.slug == EVENT_SLUG)).scalar_one_or_none()
    if existing is not None:
        print(f"Removing previous '{EVENT_SLUG}' event before reseeding...")
        db.delete(existing)
        db.commit()


def _make_event(db: Session, now) -> Event:
    event = Event(
        id=_id("event", EVENT_SLUG),
        slug=EVENT_SLUG,
        name="Load Test",
        tagline="Synthetic event for scale measurement, not a real hackathon.",
        description="Generated by scripts/load_test/seed_scale.py. Safe to delete.",
        starts_at=now - timedelta(days=10),
        ends_at=now - timedelta(days=3),
        registration_opens_at=now - timedelta(days=20),
        submission_opens_at=now - timedelta(days=18),
        submission_deadline=now - timedelta(days=5),
        judging_opens_at=now - timedelta(days=5),
        judging_closes_at=now + timedelta(days=5),
        max_team_size=1,
        is_published=True,
        voting_opens_at=now - timedelta(days=4),
        voting_closes_at=now + timedelta(days=5),
        voting_access=VotingAccess.OPEN_LINK,
        voting_method=VotingMethod.SINGLE,
        results_public_at=None,
    )
    db.add(event)
    db.flush()
    return event


CRITERIA = [
    ("impact", "Impact", Decimal("1.0")),
    ("execution", "Execution", Decimal("1.0")),
    ("craft", "Craft", Decimal("1.0")),
    ("presentation", "Presentation", Decimal("0.5")),
]


def _make_criteria(db: Session, event: Event) -> list[RubricCriterion]:
    criteria = []
    for position, (key, name, weight) in enumerate(CRITERIA):
        c = RubricCriterion(
            event_id=event.id,
            key=key,
            name=name,
            weight=weight,
            min_score=1,
            max_score=5,
            position=position,
        )
        db.add(c)
        criteria.append(c)
    db.flush()
    return criteria


def _make_submissions(db: Session, event: Event, n: int, password_hash: str) -> list[uuid.UUID]:
    print(f"Creating {n} teams + submissions (with one owning user each)...")
    submission_ids: list[uuid.UUID] = []
    now = utcnow()
    batch_users: list[User] = []
    batch_teams: list[Team] = []
    batch_members: list[TeamMember] = []
    batch_submissions: list[Submission] = []

    for i in range(n):
        user_id = uuid.uuid4()
        team_id = uuid.uuid4()
        submission_id = uuid.uuid4()
        submission_ids.append(submission_id)

        batch_users.append(
            User(
                id=user_id,
                email=f"loadtest-team-{i:06d}@example.com",
                display_name=f"Load Team {i:06d} Owner",
                password_hash=password_hash,
            )
        )
        batch_teams.append(
            Team(
                id=team_id,
                event_id=event.id,
                name=f"Load Team {i:06d}",
                invite_token=f"loadtest-{team_id.hex}",
                created_by_id=user_id,
            )
        )
        batch_members.append(
            TeamMember(team_id=team_id, user_id=user_id, event_id=event.id, team_role=TeamRole.OWNER)
        )
        batch_submissions.append(
            Submission(
                id=submission_id,
                event_id=event.id,
                team_id=team_id,
                name=f"Load Project {i:06d}",
                tagline="Synthetic project for scale measurement.",
                description="Generated by scripts/load_test/seed_scale.py.",
                repo_url=f"https://example.invalid/loadtest/{i:06d}",
                status=SubmissionStatus.SUBMITTED,
                submitted_at=now - timedelta(days=6),
            )
        )

        if len(batch_users) >= 500:
            db.add_all(batch_users)
            db.flush()
            db.add_all(batch_teams)
            db.flush()
            db.add_all(batch_members)
            db.add_all(batch_submissions)
            db.flush()
            batch_users, batch_teams, batch_members, batch_submissions = [], [], [], []

    if batch_users:
        db.add_all(batch_users)
        db.flush()
        db.add_all(batch_teams)
        db.flush()
        db.add_all(batch_members)
        db.add_all(batch_submissions)
        db.flush()

    db.commit()
    return submission_ids


def _make_judges(db: Session, event: Event, n: int, password_hash: str) -> list[uuid.UUID]:
    print(f"Creating {n} judges...")
    judge_ids: list[uuid.UUID] = []
    now = utcnow()
    batch_users: list[User] = []
    batch_judges: list[Judge] = []

    for i in range(n):
        user_id = uuid.uuid4()
        judge_id = uuid.uuid4()
        judge_ids.append(judge_id)
        batch_users.append(
            User(
                id=user_id,
                email=f"loadtest-judge-{i:05d}@example.com",
                display_name=f"Load Judge {i:05d}",
                password_hash=password_hash,
                role=Role.JUDGE,
            )
        )
        batch_judges.append(
            Judge(
                id=judge_id,
                event_id=event.id,
                user_id=user_id,
                is_active=True,
                invited_at=now - timedelta(days=6),
                accepted_at=now - timedelta(days=6),
            )
        )
        if len(batch_users) >= 500:
            db.add_all(batch_users)
            db.flush()
            db.add_all(batch_judges)
            db.flush()
            batch_users, batch_judges = [], []

    if batch_users:
        db.add_all(batch_users)
        db.flush()
        db.add_all(batch_judges)
        db.flush()

    db.commit()
    return judge_ids


def _make_ballots(
    db: Session,
    event: Event,
    submission_ids: list[uuid.UUID],
    judge_ids: list[uuid.UUID],
    criteria: list[RubricCriterion],
    reviews_per_submission: int,
) -> int:
    print(
        f"Creating {len(submission_ids) * reviews_per_submission} complete ballots "
        f"({reviews_per_submission} judges x {len(submission_ids)} submissions)..."
    )
    now = utcnow()
    rng = random.Random(1234)
    n_judges = len(judge_ids)
    total = 0
    batch_assignments: list[JudgeAssignment] = []
    batch_scores: list[Score] = []

    for si, submission_id in enumerate(submission_ids):
        # Deterministic, cheap "distinct judges per submission": a rotating
        # offset rather than `random.sample` over 500+ judges per submission,
        # since this script is not testing `app.assignment`'s own eligibility
        # rules (team conflicts, track scope, recusals) -- just producing
        # enough real, complete ballots to load-test `gather()`.
        for k in range(reviews_per_submission):
            judge_id = judge_ids[(si * reviews_per_submission + k) % n_judges]
            assignment_id = uuid.uuid4()
            completed_at = now - timedelta(hours=rng.randint(1, 96))
            batch_assignments.append(
                JudgeAssignment(
                    id=assignment_id,
                    event_id=event.id,
                    judge_id=judge_id,
                    submission_id=submission_id,
                    status=AssignmentStatus.COMPLETE,
                    completed_at=completed_at,
                )
            )
            for criterion in criteria:
                batch_scores.append(
                    Score(
                        event_id=event.id,
                        assignment_id=assignment_id,
                        criterion_id=criterion.id,
                        value=Decimal(str(rng.randint(criterion.min_score * 10, criterion.max_score * 10) / 10)),
                    )
                )
            total += 1

        if len(batch_assignments) >= 2000:
            db.add_all(batch_assignments)
            db.flush()
            db.add_all(batch_scores)
            db.flush()
            batch_assignments, batch_scores = [], []

    if batch_assignments:
        db.add_all(batch_assignments)
        db.flush()
        db.add_all(batch_scores)
        db.flush()

    db.commit()
    return total


def _make_votes(
    db: Session, event: Event, submission_ids: list[uuid.UUID], n_voters: int, votes_per_voter: int
) -> int:
    total_target = n_voters * votes_per_voter
    print(f"Creating {n_voters} voters casting {votes_per_voter} votes each ({total_target} votes)...")
    now = utcnow()
    rng = random.Random(5678)
    total = 0
    batch_voters: list[Voter] = []
    batch_votes: list[Vote] = []

    for i in range(n_voters):
        voter_id = uuid.uuid4()
        batch_voters.append(
            Voter(
                id=voter_id,
                event_id=event.id,
                access=VotingAccess.OPEN_LINK,
                token_hash=hashlib.sha256(f"loadtest-voter-{i}".encode()).hexdigest(),
                ordering_seed=i,
                last_seen_at=now - timedelta(hours=rng.randint(1, 72)),
            )
        )
        chosen = rng.sample(submission_ids, k=votes_per_voter)
        for submission_id in chosen:
            batch_votes.append(
                Vote(
                    event_id=event.id,
                    voter_id=voter_id,
                    submission_id=submission_id,
                    credits=1,
                )
            )
            total += 1

        if len(batch_voters) >= 200:
            db.add_all(batch_voters)
            db.flush()
            db.add_all(batch_votes)
            db.flush()
            batch_voters, batch_votes = [], []

    if batch_voters:
        db.add_all(batch_voters)
        db.flush()
        db.add_all(batch_votes)
        db.flush()

    db.commit()
    return total


_AUDIT_ACTIONS = [
    AuditAction.VOTE_CAST,
    AuditAction.BALLOT_SCORED,
    AuditAction.COMMENT_POSTED,
]

_SEQ_NAME_SQL = text("SELECT pg_get_serial_sequence('audit_log', 'seq')")
_CHAIN_LOCK_KEY = 0x446F_6746_6F6F_6431  # same key as app.audit._CHAIN_LOCK_KEY


def _make_audit_entries(
    db: Session, event: Event, submission_ids: list[uuid.UUID], n: int
) -> int:
    """Bulk-append `n` real, chain-valid entries onto the *global* audit log.

    Computes every hash in Python first (fast: pure CPU, no DB round trip per
    row), reusing `app.audit`'s own `_hash_fields`/`_chain_hash` so the result
    is byte-identical to what `record()` would have written one row at a time.
    Holds the same advisory lock `record()` does for the whole operation, so a
    concurrent real write can't read a head this script is about to make stale.
    """
    print(f"Creating {n} chained audit log entries (this recomputes hashes in Python, then bulk-inserts)...")
    t0 = time.time()
    rng = random.Random(9012)
    now = utcnow()

    db.execute(text("SELECT pg_advisory_xact_lock(:key)"), {"key": _CHAIN_LOCK_KEY})
    head_seq, head_hash = db.execute(
        select(AuditEntry.seq, AuditEntry.entry_hash).order_by(AuditEntry.seq.desc()).limit(1)
    ).first() or (0, None)

    rows = []
    prev_hash = head_hash
    base_time = now - timedelta(days=5)
    for i in range(n):
        seq = head_seq + 1 + i
        action = rng.choice(_AUDIT_ACTIONS)
        submission_id = rng.choice(submission_ids)
        created_at = base_time + timedelta(seconds=i * 4)
        entry = AuditEntry(
            seq=seq,
            event_id=event.id,
            event_slug=event.slug,
            action=action,
            actor_id=None,
            actor_label=f"loadtest-actor-{i % 5000}",
            actor_role="participant",
            resource_type="submission",
            resource_id=submission_id,
            summary=(
                f"Load-test synthetic entry #{i} ({action.value}) on {event.slug}"
            ),
            ip_address=None,
            created_at=created_at,
        )
        entry_hash = _chain_hash(prev_hash, entry)
        rows.append(
            {
                "id": uuid.uuid4(),
                "seq": seq,
                "event_id": entry.event_id,
                "event_slug": entry.event_slug,
                "action": action.value,
                "actor_id": None,
                "actor_label": entry.actor_label,
                "actor_role": entry.actor_role,
                "resource_type": entry.resource_type,
                "resource_id": entry.resource_id,
                "summary": entry.summary,
                "ip_address": None,
                "created_at": created_at,
                "prev_hash": prev_hash,
                "entry_hash": entry_hash,
            }
        )
        prev_hash = entry_hash

    print(f"  computed {n} hashes in {time.time() - t0:.1f}s, inserting...")

    insert_sql = text(
        """
        INSERT INTO audit_log
            (id, seq, event_id, event_slug, action, actor_id, actor_label, actor_role,
             resource_type, resource_id, summary, ip_address, created_at, prev_hash, entry_hash)
        OVERRIDING SYSTEM VALUE
        VALUES
            (:id, :seq, :event_id, :event_slug, :action, :actor_id, :actor_label, :actor_role,
             :resource_type, :resource_id, :summary, :ip_address, :created_at, :prev_hash, :entry_hash)
        """
    )
    chunk = 5000
    for start in range(0, len(rows), chunk):
        db.execute(insert_sql, rows[start : start + chunk])

    seq_name = db.execute(_SEQ_NAME_SQL).scalar_one()
    new_max_seq = head_seq + n
    db.execute(text("SELECT setval(:seq_name, :value, true)"), {"seq_name": seq_name, "value": new_max_seq})

    db.commit()
    print(f"  audit insert + sequence bump done in {time.time() - t0:.1f}s total")
    return n


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--submissions", type=int, default=1200)
    parser.add_argument("--judges", type=int, default=520)
    parser.add_argument("--reviews-per-submission", type=int, default=3)
    parser.add_argument("--voters", type=int, default=2600)
    parser.add_argument("--votes-per-voter", type=int, default=21)
    parser.add_argument("--audit-events", type=int, default=110_000)
    args = parser.parse_args()

    engine = _engine()
    SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)
    db = SessionLocal()

    t_start = time.time()
    try:
        _delete_existing_event(db)
        now = utcnow()
        event = _make_event(db, now)
        criteria = _make_criteria(db, event)
        submission_ids = _make_submissions(db, event, args.submissions, hash_password("loadtest"))
        judge_ids = _make_judges(db, event, args.judges, hash_password("loadtest"))
        n_ballots = _make_ballots(
            db, event, submission_ids, judge_ids, criteria, args.reviews_per_submission
        )
        n_votes = _make_votes(db, event, submission_ids, args.voters, args.votes_per_voter)
        n_audit = _make_audit_entries(db, event, submission_ids, args.audit_events)
    finally:
        db.close()

    elapsed = time.time() - t_start
    print()
    print("Seed complete in {:.1f}s:".format(elapsed))
    print(f"  event:       {EVENT_SLUG}")
    print(f"  submissions: {len(submission_ids)}")
    print(f"  judges:      {len(judge_ids)}")
    print(f"  ballots:     {n_ballots} ({args.reviews_per_submission} reviews/submission)")
    print(f"  votes:       {n_votes}")
    print(f"  audit rows:  {n_audit} (chained; total table size is larger)")


if __name__ == "__main__":
    main()
