"""The weighted rubric and the normalization maths.

No database, no HTTP, no fixtures -- `app.scoring` is pure functions over
dataclasses precisely so that the part of this project most likely to be argued
with can be tested with numbers a reader can check by hand.

Two kinds of assertion in here, and the split is deliberate:

* **Exact values**, where the arithmetic is simple enough to verify in your head:
  a weighted mean of two criteria, a shrinkage midpoint, a flat judge landing on
  the global mean.
* **Properties**, where it is not: that harshness cancels, that shrinkage pulls
  the right way, that ranking is invariant to things it should be invariant to.
  Asserting a hand-derived float to four places would mostly test my arithmetic.

The worked example on real fixture data lives in JUDGING.md and is generated by
`scripts/normalization_proof.py`, not by hand.
"""

from __future__ import annotations

import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parents[1] / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from app.scoring import (  # noqa: E402
    EPSILON,
    SHRINKAGE_K,
    AssignmentTiming,
    Ballot,
    Criterion,
    _mean,
    _sd,
    _shrink,
    disagreement,
    fast_completion_flags,
    judge_deviation,
    near_identical_score_flags,
    normalize,
    normalize_by_track,
    raw_score,
)


def criterion(key: str, weight: float, *, lo: int = 1, hi: int = 5) -> Criterion:
    return Criterion(
        id=uuid.uuid4(), key=key, name=key.title(), weight=weight, min_score=lo, max_score=hi
    )


# --------------------------------------------------------------------------- #
# 1. The weighted rubric
# --------------------------------------------------------------------------- #


def test_a_weighted_mean_is_a_weighted_mean() -> None:
    """impact×3 scored 5, craft×1 scored 1  ->  (15 + 1) / 4 = 4.0"""
    impact = criterion("impact", 3)
    craft = criterion("craft", 1)
    b = Ballot(uuid.uuid4(), uuid.uuid4(), {impact.id: 5, craft.id: 1})
    assert raw_score(b, [impact, craft]) == pytest.approx(4.0)


def test_the_weighted_mean_works_on_continuous_scores_too() -> None:
    """`raw_score` never assumed whole numbers -- `float(value)` was already
    the first thing it did to every score. This just says so out loud for the
    move off a discrete `scores.value` column."""
    impact = criterion("impact", 3)
    craft = criterion("craft", 1)
    b = Ballot(uuid.uuid4(), uuid.uuid4(), {impact.id: 4.5, craft.id: 3.1})
    assert raw_score(b, [impact, craft]) == pytest.approx((4.5 * 3 + 3.1) / 4)


def test_weights_are_relative_not_absolute() -> None:
    """Doubling every weight must not move a single score.

    This is the property that lets an organizer type 10 and 20 instead of 1 and 2
    without rescaling the event, and the reason weights are divided by their own
    sum at read time.
    """
    small = [criterion("a", 3), criterion("b", 1)]
    large = [
        Criterion(id=small[0].id, key="a", name="A", weight=30),
        Criterion(id=small[1].id, key="b", name="B", weight=10),
    ]
    b = Ballot(uuid.uuid4(), uuid.uuid4(), {small[0].id: 5, small[1].id: 2})
    assert raw_score(b, small) == pytest.approx(raw_score(b, large))


def test_an_equal_weighted_rubric_is_a_plain_mean() -> None:
    a, b_, c = criterion("a", 1), criterion("b", 1), criterion("c", 1)
    b = Ballot(uuid.uuid4(), uuid.uuid4(), {a.id: 1, b_.id: 4, c.id: 4})
    assert raw_score(b, [a, b_, c]) == pytest.approx(3.0)


def test_a_partial_ballot_weights_over_what_is_present() -> None:
    """A ballot missing a criterion is not scored as if that criterion were zero.

    Scoring it as zero would punish the project for the judge's incomplete work.
    The routes refuse to mark such a ballot complete, which is where that rule
    belongs; this function just declines to invent data.
    """
    impact = criterion("impact", 3)
    craft = criterion("craft", 1)
    b = Ballot(uuid.uuid4(), uuid.uuid4(), {impact.id: 4})
    assert raw_score(b, [impact, craft]) == pytest.approx(4.0)


def test_an_empty_ballot_is_none_not_zero() -> None:
    """None and 0.0 mean very different things to the mean that consumes this."""
    assert raw_score(Ballot(uuid.uuid4(), uuid.uuid4(), {}), [criterion("a", 1)]) is None


# --------------------------------------------------------------------------- #
# 2. Descriptive statistics
# --------------------------------------------------------------------------- #


def test_sd_of_one_observation_is_zero_not_undefined() -> None:
    """A judge with a single ballot has no spread. Returning 0 rather than raising
    hands them to the flat-judge rule, which is where they should be handled."""
    assert _sd([4.0]) == 0.0
    assert _sd([]) == 0.0


def test_population_sd_on_a_hand_checkable_case() -> None:
    """[1, 3]: mean 2, deviations ±1, population variance 1, sd 1."""
    assert _sd([1.0, 3.0]) == pytest.approx(1.0)


def test_shrinkage_with_n_equal_to_k_is_the_midpoint() -> None:
    assert _shrink(own=10.0, global_value=0.0, n=int(SHRINKAGE_K)) == pytest.approx(5.0)


def test_shrinkage_with_no_observations_is_the_global_value() -> None:
    assert _shrink(own=10.0, global_value=2.0, n=0) == pytest.approx(2.0)


def test_shrinkage_converges_on_the_judges_own_statistic() -> None:
    assert _shrink(own=10.0, global_value=0.0, n=10_000) == pytest.approx(10.0, abs=0.01)


# --------------------------------------------------------------------------- #
# 3. The judge who marks everything a 3
# --------------------------------------------------------------------------- #


def _one_criterion(scores_by_judge: dict[str, dict[str, int]]):
    """Build ballots for a single unit-weight criterion.

    With one criterion of weight 1, `raw == the score the judge gave`, which
    keeps these tests about normalization rather than about weighting.
    """
    only = criterion("only", 1)
    judges = {name: uuid.uuid4() for name in scores_by_judge}
    submissions: dict[str, uuid.UUID] = {}
    for per_judge in scores_by_judge.values():
        for sub in per_judge:
            submissions.setdefault(sub, uuid.uuid4())
    ballots = [
        Ballot(judges[judge], submissions[sub], {only.id: value})
        for judge, per_judge in scores_by_judge.items()
        for sub, value in per_judge.items()
    ]
    return ballots, [only], judges, submissions


def test_a_judge_who_marks_everything_the_same_is_flagged_flat() -> None:
    ballots, criteria, judges, _ = _one_criterion(
        {
            "flat": {"p1": 3, "p2": 3, "p3": 3},
            "spread": {"p1": 1, "p2": 3, "p3": 5},
        }
    )
    results = normalize(ballots, criteria)
    by_judge = {c.judge_id: c for c in results.calibrations}
    assert by_judge[judges["flat"]].flat is True
    assert by_judge[judges["spread"]].flat is False
    assert "no ordering" in by_judge[judges["flat"]].note


def test_a_flat_judge_contributes_exactly_the_global_mean() -> None:
    """Their ballots say "all of these are average", because that is the only
    thing a constant ballot can mean. Not a division by a fudge factor: an
    explicit z of zero, which maps back to the global mean on rescaling.
    """
    ballots, criteria, judges, submissions = _one_criterion(
        {
            "flat": {"p1": 3, "p2": 3, "p3": 3},
            "spread": {"p1": 1, "p2": 3, "p3": 5},
        }
    )
    results = normalize(ballots, criteria)
    flat = judges["flat"]
    for row in results.submissions:
        assert row.per_judge[flat] == pytest.approx(results.global_mean)


def test_a_flat_judge_does_not_decide_the_ranking() -> None:
    """The flat judge rates everything 5 -- the most generous possible ballot --
    and the ordering still comes entirely from the judge who discriminated."""
    ballots, criteria, judges, submissions = _one_criterion(
        {
            "generous_flat": {"p1": 5, "p2": 5, "p3": 5},
            "spread": {"p1": 1, "p2": 3, "p3": 5},
        }
    )
    results = normalize(ballots, criteria)
    ordered = [r.submission_id for r in sorted(results.submissions, key=lambda r: r.normalized_rank)]
    assert ordered == [submissions["p3"], submissions["p2"], submissions["p1"]]


def test_every_judge_flat_is_a_dead_heat_not_a_crash() -> None:
    """The degenerate case. Global sd is zero, every z is zero, everything ties --
    which is the correct answer, and the one most likely to divide by zero."""
    ballots, criteria, _, _ = _one_criterion(
        {"a": {"p1": 3, "p2": 3}, "b": {"p1": 3, "p2": 3}}
    )
    results = normalize(ballots, criteria)
    assert results.global_sd == pytest.approx(0.0)
    assert {r.normalized_rank for r in results.submissions} == {1}


# --------------------------------------------------------------------------- #
# 4. Harshness cancels
# --------------------------------------------------------------------------- #


def test_harshness_cancels_when_orderings_agree(monkeypatch) -> None:
    """THE property the whole method exists for.

    Two judges who rank three projects identically but live two points apart on
    the scale must produce the same normalized score for each project. Shrinkage
    is switched off for this one assertion, because shrinkage deliberately does
    *not* fully remove a judge effect when n is small -- that is its job -- and
    mixing the two would test neither cleanly.
    """
    monkeypatch.setattr("app.scoring.SHRINKAGE_K", 0.0)
    ballots, criteria, judges, _ = _one_criterion(
        {
            "harsh": {"p1": 1, "p2": 2, "p3": 3},
            "generous": {"p1": 3, "p2": 4, "p3": 5},
        }
    )
    results = normalize(ballots, criteria)
    for row in results.submissions:
        harsh = row.per_judge[judges["harsh"]]
        generous = row.per_judge[judges["generous"]]
        assert harsh == pytest.approx(generous), "a judge's level survived normalization"


def test_raw_scores_do_not_cancel_harshness() -> None:
    """The control for the test above: without normalization, the project the
    harsh judge happened to draw is simply worse off. This is the bug the whole
    module exists to fix, asserted so it cannot silently come back."""
    ballots, criteria, _, submissions = _one_criterion(
        {
            "harsh": {"p1": 1, "p2": 2},
            "generous": {"p3": 4, "p4": 5},
        }
    )
    results = normalize(ballots, criteria)
    raw = {r.submission_id: r.raw_mean for r in results.submissions}
    assert raw[submissions["p2"]] < raw[submissions["p3"]]


def test_a_judges_own_ordering_is_always_preserved(monkeypatch) -> None:
    """Normalization may move a project relative to others; it must never
    reorder one judge's own opinions, because a monotonic transform cannot."""
    monkeypatch.setattr("app.scoring.SHRINKAGE_K", 0.0)
    ballots, criteria, judges, submissions = _one_criterion(
        {"j": {"p1": 1, "p2": 3, "p3": 4, "p4": 5}}
    )
    results = normalize(ballots, criteria)
    # A single judge with spread: their normalized values must rise with their raw.
    j = judges["j"]
    pairs = sorted(
        ((r.raw_mean, r.per_judge[j]) for r in results.submissions), key=lambda p: p[0]
    )
    normalized_in_raw_order = [p[1] for p in pairs]
    assert normalized_in_raw_order == sorted(normalized_in_raw_order)


# --------------------------------------------------------------------------- #
# 5. Small n
# --------------------------------------------------------------------------- #


def test_a_judge_with_few_ballots_is_pulled_toward_the_field() -> None:
    """A judge with three ballots has a badly estimated mean, so we trust it less.

    Asserted as a direction rather than a value: the shrunk mean must sit between
    the judge's own and the global one, and nearer the global one than an
    unshrunk estimate would be.
    """
    ballots, criteria, judges, _ = _one_criterion(
        {
            "brief": {"p1": 5, "p2": 5, "p3": 4},
            "thorough": {f"q{i}": (i % 5) + 1 for i in range(30)},
        }
    )
    results = normalize(ballots, criteria)
    brief = next(c for c in results.calibrations if c.judge_id == judges["brief"])
    thorough = next(c for c in results.calibrations if c.judge_id == judges["thorough"])

    assert min(brief.mean, results.global_mean) <= brief.shrunk_mean <= max(
        brief.mean, results.global_mean
    )
    # The judge with 30 ballots is trusted nearly completely; the one with 3 is not.
    assert abs(thorough.shrunk_mean - thorough.mean) < abs(brief.shrunk_mean - brief.mean)
    assert "heavily shrunk" in brief.note


# --------------------------------------------------------------------------- #
# 6. Ranking
# --------------------------------------------------------------------------- #


def test_equal_scores_share_a_rank_and_the_next_one_skips() -> None:
    """Competition ranking: 1, 1, 3 -- not 1, 1, 2. Two projects genuinely tied
    for first means nothing is second."""
    ballots, criteria, _, submissions = _one_criterion(
        {"a": {"p1": 5, "p2": 5, "p3": 1}}
    )
    results = normalize(ballots, criteria)
    ranks = sorted(r.normalized_rank for r in results.submissions)
    assert ranks == [1, 1, 3]


def test_rank_delta_is_positive_when_normalization_promotes() -> None:
    """Sign convention, asserted so the dashboard cannot display it backwards."""
    ballots, criteria, _, _ = _one_criterion(
        {
            "harsh": {"p1": 1, "p2": 2, "p3": 3},
            "generous": {"p1": 5, "p2": 5, "p3": 4},
        }
    )
    results = normalize(ballots, criteria)
    for row in results.submissions:
        assert row.rank_delta == row.raw_rank - row.normalized_rank


def test_results_come_back_sorted_by_normalized_rank() -> None:
    ballots, criteria, _, _ = _one_criterion(
        {"a": {"p1": 1, "p2": 5, "p3": 3}}
    )
    results = normalize(ballots, criteria)
    assert [r.normalized_rank for r in results.submissions] == sorted(
        r.normalized_rank for r in results.submissions
    )


def test_no_ballots_is_an_empty_result_not_an_error() -> None:
    results = normalize([], [criterion("a", 1)])
    assert results.submissions == []
    assert results.global_mean == 0.0


def test_a_ballot_with_no_scores_is_ignored_entirely() -> None:
    """An assigned-but-unscored ballot must not drag a project toward zero."""
    only = criterion("only", 1)
    sub = uuid.uuid4()
    ballots = [
        Ballot(uuid.uuid4(), sub, {only.id: 4}),
        Ballot(uuid.uuid4(), sub, {}),  # assigned, never filled in
    ]
    results = normalize(ballots, [only])
    row = results.by_id(sub)
    assert row is not None
    assert row.n_reviews == 1
    assert row.raw_mean == pytest.approx(4.0)


# --------------------------------------------------------------------------- #
# 4. Per-track normalization
# --------------------------------------------------------------------------- #


def test_a_single_track_group_matches_plain_normalize() -> None:
    """`normalize_by_track` must be a strict generalisation: one track (or
    none) is the common case and has to behave exactly like `normalize`."""
    ballots, criteria, _, submissions = _one_criterion(
        {"a": {"p1": 1, "p2": 3, "p3": 5}, "b": {"p1": 2, "p2": 3, "p3": 4}}
    )
    plain = normalize(ballots, criteria)
    track_of = {sub: None for sub in submissions.values()}
    tracked = normalize_by_track(ballots, criteria, track_of)

    plain_by_id = {r.submission_id: r.normalized_mean for r in plain.submissions}
    tracked_by_id = {r.submission_id: r.normalized_mean for r in tracked.submissions}
    assert plain_by_id == pytest.approx(tracked_by_id)


def test_a_cross_track_judge_gets_one_calibration_per_track() -> None:
    """The bug this function exists to fix: a judge who reviews two tracks
    harshly on one and generously on the other must not be averaged into a
    single, wrong calibration for both."""
    only = criterion("only", 1)
    judge = uuid.uuid4()
    a1, a2, b1, b2 = (uuid.uuid4() for _ in range(4))
    track_a, track_b = uuid.uuid4(), uuid.uuid4()
    ballots = [
        Ballot(judge, a1, {only.id: 1}),
        Ballot(judge, a2, {only.id: 1}),
        Ballot(judge, b1, {only.id: 5}),
        Ballot(judge, b2, {only.id: 5}),
    ]
    track_of = {a1: track_a, a2: track_a, b1: track_b, b2: track_b}

    result = normalize_by_track(ballots, [only], track_of)
    cals = [c for c in result.calibrations if c.judge_id == judge]
    assert len(cals) == 2
    means = sorted(c.mean for c in cals)
    assert means == [pytest.approx(1.0), pytest.approx(5.0)]
    tracks = {c.track_id for c in cals}
    assert tracks == {track_a, track_b}


def test_track_restricted_judges_are_untouched_by_normalize_by_track() -> None:
    """A judge who only ever sees one track produces exactly the calibration
    they would from plain `normalize` scoped to that track alone."""
    ballots, criteria, judges, submissions = _one_criterion(
        {"harsh": {"p1": 1, "p2": 2}, "generous": {"p1": 5, "p2": 4}}
    )
    track = uuid.uuid4()
    track_of = {sub: track for sub in submissions.values()}
    result = normalize_by_track(ballots, criteria, track_of)
    assert len(result.calibrations) == 2
    assert all(c.track_id == track for c in result.calibrations)


# --------------------------------------------------------------------------- #
# 5. Inter-rater reliability
# --------------------------------------------------------------------------- #


def test_judges_who_agree_are_not_flagged() -> None:
    ballots, criteria, _, submissions = _one_criterion(
        {"a": {"p1": 4, "p2": 3}, "b": {"p1": 4, "p2": 3}}
    )
    rows = disagreement(normalize(ballots, criteria))
    assert all(not r.needs_review for r in rows)
    assert all(r.mean_abs_pairwise_diff == pytest.approx(0.0) for r in rows)


def test_judges_who_disagree_wildly_are_flagged() -> None:
    """Each judge needs more than one ballot here on purpose: with exactly one,
    a judge's own `sd` is 0 by definition (see `_sd`) and they are classified
    `flat` -- correctly, since one data point has no measurable spread -- which
    would map both judges to the global mean and hide the disagreement this
    test exists to catch. A real disagreement signal needs judges who have
    demonstrated they *can* discriminate, and then didn't agree on `p1`.
    """
    ballots, criteria, _, submissions = _one_criterion(
        {
            "harsh": {"p1": 1, "p2": 3, "p3": 5},
            "generous": {"p1": 5, "p2": 3, "p3": 1},
        }
    )
    rows = disagreement(normalize(ballots, criteria))
    by_id = {r.submission_id: r for r in rows}
    p1 = by_id[submissions["p1"]]
    assert p1.needs_review is True
    assert p1.mean_abs_pairwise_diff > 0
    # p2 (3 and 3) is where the two judges agree, and must not be flagged.
    assert by_id[submissions["p2"]].needs_review is False


def test_a_lone_review_is_not_flagged_for_low_coverage() -> None:
    """One review cannot disagree with itself -- this is a coverage gap, not a
    disagreement, and `disagreement()` must not conflate the two."""
    ballots, criteria, _, _ = _one_criterion({"a": {"p1": 3}})
    rows = disagreement(normalize(ballots, criteria))
    assert len(rows) == 1
    assert rows[0].n_reviews == 1
    assert rows[0].needs_review is False
    assert rows[0].sd == 0.0


def test_disagreement_rows_are_sorted_worst_first() -> None:
    ballots, criteria, _, _ = _one_criterion(
        {
            "a": {"p1": 3, "p2": 3, "p3": 1},
            "b": {"p1": 3, "p2": 4, "p3": 5},
        }
    )
    rows = disagreement(normalize(ballots, criteria))
    diffs = [r.mean_abs_pairwise_diff for r in rows]
    assert diffs == sorted(diffs, reverse=True)


def test_a_judge_who_disagrees_with_consensus_is_flagged() -> None:
    """Calibration would call this judge merely harsh; after normalization
    already corrects for that, this judge *still* disagrees -- that residual
    is what `judge_deviation` measures and calibration cannot."""
    ballots, criteria, judges, _ = _one_criterion(
        {
            # Two judges agree closely across the board...
            "a": {"p1": 4, "p2": 3, "p3": 2},
            "b": {"p1": 4, "p2": 3, "p3": 2},
            # ...a third disagrees with the room on which project is best,
            # not just about how generous to be overall.
            "c": {"p1": 1, "p2": 4, "p3": 5},
        }
    )
    rows = judge_deviation(normalize(ballots, criteria))
    by_judge = {r.judge_id: r.mean_abs_deviation for r in rows}
    assert by_judge[judges["c"]] > by_judge[judges["a"]]
    assert by_judge[judges["c"]] > by_judge[judges["b"]]


# --------------------------------------------------------------------------- #
# 6. Judge consistency: signals for organizer review only
# --------------------------------------------------------------------------- #


def test_a_judge_with_no_spread_across_many_ballots_is_flagged() -> None:
    """4+ ballots, every one the same value -- the same pattern `flat` catches
    for scoring purposes, but here gated on `min_reviews` so it reads as a
    real pattern (many independent ballots, zero spread) rather than firing
    on a single low-information data point the way `flat` correctly does."""
    ballots, criteria, judges, _ = _one_criterion(
        {
            "uniform": {"p1": 3, "p2": 3, "p3": 3, "p4": 3},
            "normal": {"p1": 1, "p2": 3, "p3": 5, "p4": 2},
        }
    )
    flags = near_identical_score_flags(normalize(ballots, criteria))
    flagged_judges = {f.judge_id for f in flags}
    assert judges["uniform"] in flagged_judges
    assert judges["normal"] not in flagged_judges
    assert all(f.reason == "near_identical_scores" for f in flags)


def test_a_judge_with_too_few_ballots_is_not_flagged_even_if_uniform() -> None:
    """Two identical-looking ballots is not a pattern -- `min_reviews` gates
    this signal so a judge is not flagged on essentially no evidence."""
    ballots, criteria, judges, _ = _one_criterion({"new": {"p1": 3, "p2": 3}})
    flags = near_identical_score_flags(normalize(ballots, criteria))
    assert judges["new"] not in {f.judge_id for f in flags}


def test_near_identical_thresholds_are_configurable() -> None:
    ballots, criteria, judges, _ = _one_criterion({"a": {"p1": 3, "p2": 3, "p3": 3, "p4": 3}})
    results = normalize(ballots, criteria)
    assert near_identical_score_flags(results, min_reviews=10) == []
    assert near_identical_score_flags(results, sd_threshold=-1.0) == []


# One reference instant for the whole module. Only the gaps between a judge's
# completions matter to the signal, so it does not have to be any particular date.
_BASE = datetime.now(timezone.utc)


def _timing(judge: uuid.UUID, submission: uuid.UUID, seconds_offset: float) -> AssignmentTiming:
    return AssignmentTiming(
        judge_id=judge, submission_id=submission, completed_at=_BASE + timedelta(seconds=seconds_offset)
    )


def test_two_ballots_finished_seconds_apart_are_flagged() -> None:
    judge, a, b = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    timings = [_timing(judge, a, 0), _timing(judge, b, 5)]
    flags = fast_completion_flags(timings)
    assert len(flags) == 1
    assert flags[0].judge_id == judge
    assert flags[0].reason == "fast_completion"


def test_ballots_finished_far_apart_are_not_flagged() -> None:
    judge, a, b = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    timings = [_timing(judge, a, 0), _timing(judge, b, 3600)]
    assert fast_completion_flags(timings) == []


def test_a_single_completed_ballot_has_nothing_to_compare_against() -> None:
    judge, a = uuid.uuid4(), uuid.uuid4()
    assert fast_completion_flags([_timing(judge, a, 0)]) == []


def test_fast_completion_is_scoped_per_judge() -> None:
    """Two different judges each finishing a ballot around the same moment is
    not a pattern -- the gap only means something between the *same* judge's
    consecutive completions."""
    judge_a, judge_b, sub_a, sub_b = uuid.uuid4(), uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    timings = [_timing(judge_a, sub_a, 0), _timing(judge_b, sub_b, 2)]
    assert fast_completion_flags(timings) == []


def test_fast_completion_threshold_is_configurable() -> None:
    judge, a, b = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    timings = [_timing(judge, a, 0), _timing(judge, b, 5)]
    assert fast_completion_flags(timings, threshold_seconds=1.0) == []
    assert len(fast_completion_flags(timings, threshold_seconds=10.0)) == 1
