"""submission discord usernames and linkedin url

Revision ID: 84c3bf9d47e2
Revises: 4bef2bf4c0a8

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84c3bf9d47e2'
down_revision: Union[str, Sequence[str], None] = '4bef2bf4c0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('linkedin_url', sa.String(length=2048), nullable=True))
    # `server_default` for the same reason every other NOT NULL column added
    # to a non-empty table needs one here: an existing submission needs a real
    # value the moment the column exists, not just for rows inserted after.
    op.add_column(
        'submissions',
        sa.Column(
            'discord_usernames', postgresql.ARRAY(sa.Text()), nullable=False, server_default='{}'
        ),
    )
    op.alter_column('submissions', 'discord_usernames', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'discord_usernames')
    op.drop_column('submissions', 'linkedin_url')
    # ### end Alembic commands ###
