"""per-event registration, winner and community-vote slots

Revision ID: 9070e8444b3a
Revises: b5eb765b806c

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9070e8444b3a'
down_revision: Union[str, Sequence[str], None] = 'b5eb765b806c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('discord_username', sa.String(length=64), nullable=False),
    sa.Column('is_team_leader', sa.Boolean(), nullable=False),
    sa.Column('leader_name', sa.String(length=160), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_registrations_event_user')
    )
    # `server_default` here, not just the ORM-level default: an event row
    # created before this migration needs a real value the moment the column
    # exists. Dropped again once backfilled so the only default going forward
    # is the one the model declares.
    op.add_column(
        'events', sa.Column('winner_slots', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'events',
        sa.Column('community_vote_slots', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('events', 'winner_slots', server_default=None)
    op.alter_column('events', 'community_vote_slots', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'community_vote_slots')
    op.drop_column('events', 'winner_slots')
    op.drop_table('event_registrations')
    # ### end Alembic commands ###
