"""judging integrity: adjudication flag, recusals

Revision ID: b5eb765b806c
Revises: dae9c25aa5fa

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5eb765b806c'
down_revision: Union[str, Sequence[str], None] = 'dae9c25aa5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge_recusals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id', 'event_id'], ['judges.id', 'judges.event_id'], name='fk_judge_recusals_judge_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id', 'event_id'], ['submissions.id', 'submissions.event_id'], name='fk_judge_recusals_submission_same_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_id', 'submission_id', name='uq_judge_recusals_once')
    )
    # `server_default` here, not just the ORM-level default: existing rows on an
    # event that already has ballots need a real value the moment the column
    # exists, not just for rows inserted after this migration runs. Dropped
    # again once backfilled so the column's only default going forward is the
    # one the model declares.
    op.add_column(
        'judge_assignments',
        sa.Column('is_adjudication', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('judge_assignments', 'is_adjudication', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judge_assignments', 'is_adjudication')
    op.drop_table('judge_recusals')
    # ### end Alembic commands ###
