"""baseline

Revision ID: dae9c25aa5fa
Revises:

Everything this project's schema is as of the end of Phase 5, in one migration
rather than five phases' worth of incremental ones. `create_all()` was honest for
a greenfield schema and had no answer for altering a column that changed
underneath it -- this is that answer for every deployment from here forward.
Generated with `alembic revision --autogenerate` against an empty database and
verified: applied to a fresh database and diffed against `Base.metadata` with
`alembic check` (clean, zero further operations -- this migration's schema and
the ORM's are identical), and the generated `downgrade()` removes every object
it created. The test suite still builds its schema with `Base.metadata.create_all()`
directly rather than through this migration, which `alembic check`'s result is
exactly what makes safe: the two are proven identical, so a schema either one
builds is the schema the tests run against.

New schema changes from here on are incremental migrations on top of this one,
generated with `alembic revision --autogenerate -m "..."` and reviewed before
being committed -- autogenerate is a first draft, not a substitute for reading
what it proposes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae9c25aa5fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('count >= 0', name='ck_rate_limits_count_nonnegative'),
    sa.PrimaryKeyConstraint('key', 'window_started_at')
    )
    op.create_index('ix_rate_limits_window', 'rate_limits', ['window_started_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('visitor', 'participant', 'judge', 'organizer', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lowercase'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('judging_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('judging_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('voting_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_access', sa.Enum('open_link', 'email_gated', 'authenticated', name='voting_access_mode'), nullable=False),
    sa.Column('voting_method', sa.Enum('single', 'quadratic', name='voting_method'), nullable=False),
    sa.Column('vote_credits', sa.Integer(), nullable=False),
    sa.Column('votes_per_voter', sa.Integer(), nullable=False),
    sa.Column('results_public_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False),
    sa.Column('pairwise_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at >= starts_at', name='ck_events_dates_ordered'),
    sa.CheckConstraint('max_team_size >= 1', name='ck_events_team_size_positive'),
    sa.CheckConstraint('submission_deadline >= submission_opens_at', name='ck_events_submission_window'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_events_published', 'events', ['is_published'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('event_slug', sa.String(length=80), nullable=True),
    sa.Column('action', sa.Enum('vote_cast', 'vote_changed', 'vote_withdrawn', 'ballot_scored', 'comment_posted', 'comment_hidden', 'judge_invited', 'judge_deactivated', 'assignment_run', 'assignment_deleted', 'rubric_changed', 'results_published', 'submission_edited_after_deadline', 'role_changed', 'rate_limited', 'webhook_registered', 'webhook_removed', 'certificate_issued', 'certificate_revoked', 'bulk_import', 'bulk_import_undone', 'event_created', 'event_changed', 'event_deleted', 'event_config_changed', 'team_created', 'team_changed', 'team_deleted', 'team_joined', 'team_member_removed', 'invite_rotated', 'judge_removed', 'account_deactivated', 'account_reactivated', 'pairwise_compared', name='audit_action'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('length(btrim(summary)) > 0', name='ck_audit_summary_not_blank'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq', name='uq_audit_log_seq')
    )
    op.create_index('ix_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_event_created', 'audit_log', ['event_id', 'created_at'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('participation', 'judging', 'placement', name='certificate_kind'), nullable=False),
    sa.Column('subject_user_id', sa.Uuid(), nullable=True),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=300), nullable=True),
    sa.CheckConstraint('(revoked_at IS NULL AND revoked_reason IS NULL) OR (revoked_at IS NOT NULL AND revoked_reason IS NOT NULL)', name='ck_certificates_revocation_has_reason'),
    sa.CheckConstraint('subject_user_id IS NOT NULL OR submission_id IS NOT NULL', name='ck_certificates_has_subject'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_certificates_event_id', 'certificates', ['event_id'], unique=False)
    op.create_index('uq_certificates_event_kind_submission', 'certificates', ['event_id', 'kind', 'submission_id'], unique=True, postgresql_where=sa.text('submission_id IS NOT NULL'))
    op.create_index('uq_certificates_event_kind_user', 'certificates', ['event_id', 'kind', 'subject_user_id'], unique=True, postgresql_where=sa.text('subject_user_id IS NOT NULL'))
    op.create_table('event_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('text', 'textarea', 'url', 'select', 'checkbox', name='question_kind'), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_questions_event_id', 'event_questions', ['event_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_score > min_score', name='ck_rubric_criteria_range'),
    sa.CheckConstraint('weight > 0', name='ck_rubric_criteria_weight_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'key', name='uq_rubric_criteria_event_key'),
    sa.UniqueConstraint('id', 'event_id', name='uq_rubric_criteria_id_event')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_teams_event_name'),
    sa.UniqueConstraint('id', 'event_id', name='uq_teams_id_event'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'key', name='uq_tracks_event_key'),
    sa.UniqueConstraint('id', 'event_id', name='uq_tracks_id_event')
    )
    op.create_table('voters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('access', sa.Enum('open_link', 'email_gated', 'authenticated', name='voting_access'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('ordering_seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.CheckConstraint('email IS NULL OR email = lower(email)', name='ck_voters_email_lower'),
    sa.CheckConstraint('user_id IS NOT NULL OR email IS NOT NULL OR token_hash IS NOT NULL', name='ck_voters_identified'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'event_id', name='uq_voters_id_event'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_voters_event_id', 'voters', ['event_id'], unique=False)
    op.create_index('uq_voters_event_email', 'voters', ['event_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_voters_event_user', 'voters', ['event_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failure_count >= 0', name='ck_webhooks_failures_nonnegative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'url', name='uq_webhooks_event_url'),
    sa.UniqueConstraint('id', 'event_id', name='uq_webhooks_id_event')
    )
    op.create_index('ix_webhooks_event_id', 'webhooks', ['event_id'], unique=False)
    op.create_table('judges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id', 'event_id'], ['tracks.id', 'tracks.event_id'], name='fk_judges_track_same_event', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_judges_event_user'),
    sa.UniqueConstraint('id', 'event_id', name='uq_judges_id_event')
    )
    op.create_index('ix_judges_event_id', 'judges', ['event_id'], unique=False)
    op.create_table('prizes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id', 'event_id'], ['tracks.id', 'tracks.event_id'], name='fk_prizes_track_same_event', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prizes_event_id', 'prizes', ['event_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('gallery_image_urls', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('demo_video_url', sa.String(length=2048), nullable=True),
    sa.Column('repo_url', sa.String(length=2048), nullable=True),
    sa.Column('live_url', sa.String(length=2048), nullable=True),
    sa.Column('tech_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', name='submission_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND submitted_at IS NULL) OR (status = 'submitted' AND submitted_at IS NOT NULL)", name='ck_submissions_submitted_at_matches_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id', 'event_id'], ['teams.id', 'teams.event_id'], name='fk_submissions_team_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id', 'event_id'], ['tracks.id', 'tracks.event_id'], name='fk_submissions_track_same_event', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'event_id', name='uq_submissions_id_event'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index('ix_submissions_event_status', 'submissions', ['event_id', 'status'], unique=False)
    op.create_index('ix_submissions_tech_tags', 'submissions', ['tech_tags'], unique=False, postgresql_using='gin')
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('team_role', sa.Enum('owner', 'member', name='team_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id', 'event_id'], ['teams.id', 'teams.event_id'], name='fk_team_members_team_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_team_members_one_team_per_event')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', 'blocked', name='delivery_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id', 'event_id'], ['webhooks.id', 'webhooks.event_id'], name='fk_deliveries_webhook_same_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_event_created', 'webhook_deliveries', ['event_id', 'created_at'], unique=False)
    op.create_index('ix_deliveries_status', 'webhook_deliveries', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('hidden_by_id', sa.Uuid(), nullable=True),
    sa.Column('hidden_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_hidden = false AND hidden_by_id IS NULL) OR (is_hidden = true AND hidden_by_id IS NOT NULL)', name='ck_comments_hidden_has_moderator'),
    sa.CheckConstraint('length(btrim(body)) > 0', name='ck_comments_body_not_blank'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hidden_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id', 'event_id'], ['submissions.id', 'submissions.event_id'], name='fk_comments_submission_same_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_submission', 'comments', ['submission_id'], unique=False)
    op.create_table('judge_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'complete', name='assignment_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id', 'event_id'], ['judges.id', 'judges.event_id'], name='fk_judge_assignments_judge_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id', 'event_id'], ['submissions.id', 'submissions.event_id'], name='fk_judge_assignments_submission_same_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'event_id', name='uq_judge_assignments_id_event'),
    sa.UniqueConstraint('judge_id', 'submission_id', name='uq_judge_assignments_once')
    )
    op.create_index('ix_judge_assignments_event_status', 'judge_assignments', ['event_id', 'status'], unique=False)
    op.create_index('ix_judge_assignments_submission', 'judge_assignments', ['submission_id'], unique=False)
    op.create_table('pairwise_comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('submission_a_id', sa.Uuid(), nullable=False),
    sa.Column('submission_b_id', sa.Uuid(), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('submission_a_id != submission_b_id', name='ck_pairwise_distinct_submissions'),
    sa.CheckConstraint('winner_id IS NULL OR winner_id = submission_a_id OR winner_id = submission_b_id', name='ck_pairwise_winner_is_a_or_b'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id', 'event_id'], ['judges.id', 'judges.event_id'], name='fk_pairwise_judge_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_a_id', 'event_id'], ['submissions.id', 'submissions.event_id'], name='fk_pairwise_a_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_b_id', 'event_id'], ['submissions.id', 'submissions.event_id'], name='fk_pairwise_b_same_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pairwise_event', 'pairwise_comparisons', ['event_id'], unique=False)
    op.create_index('ix_pairwise_judge', 'pairwise_comparisons', ['judge_id'], unique=False)
    op.create_table('submission_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['event_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_submission_answers_one_each')
    )
    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name='ck_votes_credits_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id', 'event_id'], ['submissions.id', 'submissions.event_id'], name='fk_votes_submission_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id', 'event_id'], ['voters.id', 'voters.event_id'], name='fk_votes_voter_same_event', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_id', 'submission_id', name='uq_votes_one_per_project')
    )
    op.create_index('ix_votes_submission', 'votes', ['submission_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id', 'event_id'], ['judge_assignments.id', 'judge_assignments.event_id'], name='fk_scores_assignment_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_id', 'event_id'], ['rubric_criteria.id', 'rubric_criteria.event_id'], name='fk_scores_criterion_same_event', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'criterion_id', name='uq_scores_one_per_criterion')
    )
    op.create_index('ix_scores_event_id', 'scores', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_event_id', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_votes_submission', table_name='votes')
    op.drop_table('votes')
    op.drop_table('submission_answers')
    op.drop_index('ix_pairwise_judge', table_name='pairwise_comparisons')
    op.drop_index('ix_pairwise_event', table_name='pairwise_comparisons')
    op.drop_table('pairwise_comparisons')
    op.drop_index('ix_judge_assignments_submission', table_name='judge_assignments')
    op.drop_index('ix_judge_assignments_event_status', table_name='judge_assignments')
    op.drop_table('judge_assignments')
    op.drop_index('ix_comments_submission', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_deliveries_status', table_name='webhook_deliveries')
    op.drop_index('ix_deliveries_event_created', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_table('team_members')
    op.drop_index('ix_submissions_tech_tags', table_name='submissions', postgresql_using='gin')
    op.drop_index('ix_submissions_event_status', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_prizes_event_id', table_name='prizes')
    op.drop_table('prizes')
    op.drop_index('ix_judges_event_id', table_name='judges')
    op.drop_table('judges')
    op.drop_index('ix_webhooks_event_id', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index('uq_voters_event_user', table_name='voters', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_voters_event_email', table_name='voters', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('ix_voters_event_id', table_name='voters')
    op.drop_table('voters')
    op.drop_table('tracks')
    op.drop_table('teams')
    op.drop_table('rubric_criteria')
    op.drop_index('ix_event_questions_event_id', table_name='event_questions')
    op.drop_table('event_questions')
    op.drop_index('uq_certificates_event_kind_user', table_name='certificates', postgresql_where=sa.text('subject_user_id IS NOT NULL'))
    op.drop_index('uq_certificates_event_kind_submission', table_name='certificates', postgresql_where=sa.text('submission_id IS NOT NULL'))
    op.drop_index('ix_certificates_event_id', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_audit_event_created', table_name='audit_log')
    op.drop_index('ix_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_events_published', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_rate_limits_window', table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
